const products = [
  {
    id: 1,
    name: "Tubo Mueble Cuadrado Esp 1.10 un 3/4 Primera - Norma Ntc 1986",
    description: "Presentamos la nueva placa colaborante que se puede utilizar por ambas caras. Su innovador diseño alcanza un metro de ancho útil, es rápida en su instalación, liviana y de gran capacidad de carga. Fabricada con altos estándares de calidad y a la medida requerida, esta placa es la mejor opción para entrepisos.",
    image: "/images/Frame142.png",
    price: "9.99",
    stock: 10,
    discount: "20%",
    quantity: 1,
    options: {
      paquete: ["Seleccione una opción", "Paquete 2", "Paquete 3"],
      longitud: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      ancho: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      colorExterno: ["#E32119", "#BDBDBD", "#3C3C3B", "#BDBDBD"],
      colorInterno: ["#F2F2F2", "#3C3C3B", "#000000"],
    },
    subtotal: 9.99
  },
  {
    id: 2,
    name: "Plancha Hot Rolled Esp 6.00 un 1829x6096 Primera",
    description: "Lorem ipsum",
    image: "/images/prod3.jpg",
    price: "19.99",
    stock: 20,
    discount: "20%",
    quantity: 1,
    options: {
       paquete: ["Seleccione una opción", "Paquete 2", "Paquete 3"],
      longitud: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      ancho: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      colorExterno: ["#E32119", "#BDBDBD", "#3C3C3B", "#BDBDBD"],
      colorInterno: ["#F2F2F2", "#3C3C3B", "#000000"],
    },
    subtotal: 19.99
  },
  {
    id: 3,
    name: "Marco Ventana Corriente Esp 1.00 un 6.00 mt Primera",
    description: "Lorem ipsum",
    image: "/images/prod4.jpg",
    price: "29.99",
    stock: 30,
    discount: "20%",
    quantity: 1,
    options: {
      paquete: ["Seleccione una opción", "Paquete 2", "Paquete 3"],
      longitud: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      ancho: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      colorExterno: ["#E32119", "#BDBDBD", "#3C3C3B", "#BDBDBD"],
      colorInterno: ["#F2F2F2", "#3C3C3B", "#000000"],
    },
    subtotal: 29.99
  },
  {
    id: 4,
    name: "Varilla Corrugada Esp 1/4 x 6 un Primera",
    description: "Lorem ipsum",
    image: "/images/prod4.jpg",
    price: "29.99",
    stock: 30,
    discount: "20%",
    quantity: 1,
    options: {
      paquete: ["Seleccione una opción", "Paquete 2", "Paquete 3"],
      longitud: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      ancho: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      colorExterno: ["#E32119", "#BDBDBD", "#3C3C3B", "#BDBDBD"],
      colorInterno: ["#F2F2F2", "#3C3C3B", "#000000"],
    },
    subtotal: 29.99
  },
  {
    id: 5,
    name: "Varilla Corrugada Esp 1/4 x 6 un Primera",
    description: "Lorem ipsum",
    image: "/images/prod4.jpg",
    price: "29.99",
    stock: 30,
    discount: "20%",
    quantity: 1,
    options: {
      paquete: ["Seleccione una opción", "Paquete 2", "Paquete 3"],
      longitud: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      ancho: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      colorExterno: ["#E32119", "#BDBDBD", "#3C3C3B", "#BDBDBD"],
      colorInterno: ["#F2F2F2", "#3C3C3B", "#000000"],
    },
    subtotal: 29.99
  },
  {
    id: 6,
    name: "Varilla Corrugada Esp 1/4 x 6 un Primera",
    description: "Lorem ipsum",
    image: "/images/prod4.jpg",
    price: "29.99",
    stock: 30,
    discount: "20%",
    quantity: 1,
    options: {
       paquete: ["Seleccione una opción", "Paquete 2", "Paquete 3"],
      longitud: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      ancho: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      colorExterno: ["#E32119", "#BDBDBD", "#3C3C3B", "#BDBDBD"],
      colorInterno: ["#F2F2F2", "#3C3C3B", "#000000"],
    },
    subtotal: 29.99
  },
  {
    id: 7,
    name: "Varilla Corrugada Esp 1/4 x 6 un Primera",
    description: "Lorem ipsum",
    image: "/images/prod4.jpg",
    price: "29.99",
    stock: 30,
    discount: "20%",
    quantity: 1,
    options: {
       paquete: ["Seleccione una opción", "Paquete 2", "Paquete 3"],
      longitud: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      ancho: ["Seleccione una opción", "1.10 mm", "1.20 mm"],
      colorExterno: ["#E32119", "#BDBDBD", "#3C3C3B", "#BDBDBD"],
      colorInterno: ["#F2F2F2", "#3C3C3B", "#000000"],
    },
    subtotal: 29.99
  },
]

export default products